Medyalar/Controllers/MedyasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medyalar.Data;
using Medyalar.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Medyalar.Controllers
{
    public class MedyasController : Controller
    {
        private readonly MedyalarContext _context;
        private IRepository _repository;
        private readonly IWebHostEnvironment _whe;

        public MedyasController(MedyalarContext context, IRepository repository, IWebHostEnvironment whe)
        {
            _context = context;
            _repository = repository;
            _whe = whe;
        }

        // GET: Medyas
        public IActionResult Index()
        {
            var medya = _repository.GetMedyas();
            return View(medya);
        }

        // GET: Medyas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medya = await _context.Medya
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medya == null)
            {
                return NotFound();
            }

            return View(medya);
        }

        // GET: Medyas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medyas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Medya medya, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                //if (file!=null)
                //{
                    //var extn = Path.GetExtension(file.FileName);
                    //var randomName = ($"{Guid.NewGuid()}{extn}");
                    //var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\files", randomName);
                    //using(var stream=new FileStream(path, FileMode.Create))
                    //{
                    //    await file.CopyToAsync(stream);
                    //}

                //    var local_file_dir = $"wwwroot/uploads/files";
                //    var local_file_path = $"{local_file_dir}/{file.FileName}";  //exception
                //    if (!Directory.Exists(Path.Combine(local_file_dir)))  //dosya yoksa oluştur
                //        Directory.CreateDirectory(Path.Combine(local_file_dir));
                    
                //    using (Stream fileStream = new FileStream(local_file_path, FileMode.Create))  //dosya kaydet
                //    {
                //        file.CopyTo(fileStream);
                //    }
                //medya.DosyaAdi = $"{local_file_dir}{file.FileName}";
                //}
                



                //var files = HttpContext.Request.Form.Files;

                //if (files.Count > 0)
                //{
                //    var fileName = Guid.NewGuid().ToString();

                //    var uploads = Path.Combine(_whe.WebRootPath, @"uploads\files");
                //    var extn = Path.GetExtension(files[0].FileName);

                //    if (medya.DosyaAdi != null)
                //    {
                //        var path = Path.Combine(_whe.WebRootPath, medya.DosyaAdi.TrimStart('\\'));

                //        if (System.IO.File.Exists(path))
                //        {
                //            System.IO.File.Delete(path);
                //        }
                //    }
                //    using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extn), FileMode.Create))
                //    {
                //        files[0].CopyTo(filesStreams);
                //    }
                //    medya.DosyaAdi = @"uploads\files\" + fileName + extn;
                //}
                _context.Add(medya);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medya);
        }

        // GET: Medyas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medya = await _context.Medya.FindAsync(id);
            if (medya == null)
            {
                return NotFound();
            }
            return View(medya);
        }

        // POST: Medyas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Medya medya)
        {
            _repository.UpdateMedya(medya);
            return RedirectToAction(nameof(Index));

        }

        // GET: Medyas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medya = await _context.Medya
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medya == null)
            {
                return NotFound();
            }

            return View(medya);
        }

        // POST: Medyas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medya = await _context.Medya.FindAsync(id);
            //TempData["Message"] = "Kayıt sistemden tamamen silinecek. Bu işlem geri alınamaz.";

            var path = Path.Combine(_whe.WebRootPath, medya.DosyaAdi.TrimStart('\\'));

            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);

            }

            _context.Medya.Remove(medya);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedyaExists(int id)
        {
            return _context.Medya.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ArchiveData(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medya = await _context.Medya
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medya == null)
            {
                return NotFound();
            }

            return View(medya);
        }

        [HttpPost, ActionName("ArchiveData")]
        [ValidateAntiForgeryToken]
        public IActionResult ArchiveData(Medya medya)
        {
            _repository.Arsivle(medya);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Archived()
        {
            //var archived = _repository.Medya.Where(m => m.isArchived == true).ToList();
            var archived = _repository.GetMedyasByArchived(true);
            return View(archived);
        }
    }
}

Medyalar/Views/Shared/_Layout.cshtml
@using Medyalar.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medyalar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Medyas" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medyas" asp-action="Index">Data</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*<div id="myModalDelete" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <img src="/Images/x-image.png" />
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div id="myModalAlertBody" class="modal-body alert">
                            this is a modal body.
                        </div>
                        <div class="modal-footer">
                            &nbsp;
                            <button type="button" class="btn" data-dismiss="modal">İptal</button>
                            <button type="button" class="btn">Tamam</button>
                        </div>
                    </div>
                </div>
            </div>*@
            @RenderBody()
        </main>

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>